### ISSUE TITLE
Addon v6.1 Always Returns true for Simple Data Type on Thunderbird 128.3.2esr

### ISSUE THREAD

**Issue by jasineri** [electrotype/thunderbird-addon-scriptable-notifications#19]
Since updating to Thunderbird version 128.3.2esr (64-bit) on Linux Debian 6.11.2-amd64, I’ve encountered an issue with addon version 6.1. The addon consistently returns true for the simple data type sent to the native script, even when there are no unread messages. This behavior seems incorrect and may indicate a bug.

**Comment by electrotype** [comment]
Hi,

I'm unable to reproduce that on Thunderbird 128.4.0esr (64-bit), Linux.

What happens if you click the "true" and "false" test buttons in the options?

Also, in order to easily try to reproduce the bug, I selected two read messages in a folder that is monitored, right-click them and "Mark / As Unread". Then I read one of them and my script is triggered properly indicating there is still one unread message. I read the last message and my script indicates there are no more unread message.

If you're not using one of the provided script, maybe you could try one to first see if the issue is not in your custom script?

**Comment by jasineri** [comment]
Clicking the test buttons works as expected!
However, your second suggestion to test by marking as read/unread works as follows:
(assuming all messages are initially marked as read)    
    Marking the 1st message as unread: Nothing triggered (incorrect).
    Marking the 2nd message as unread: Nothing triggered (incorrect).
    Marking the 1st message as read: "True" triggered (correct).
    Marking the 2nd message as read: "True" triggered (incorrect).
By the way, I'm using one of the provided scripts with minimal changes.

**Comment by electrotype** [comment]
```
Marking the 1st message as unread: Nothing triggered (incorrect).

Marking the 2nd message as unread: Nothing triggered (incorrect).
```

Those are in fact correct. The script is only triggered when you _read_ (or delete) a message.

```
Marking the 2nd message as read: "True" triggered (incorrect).
```

This one is indeed incorrect if all messages are then read.

I'm not sure what to suggest here. Can you unselect all "Mail/Feed folders to monitor" in the options and start again? It's like the extension sees there is still an unread message in some of the monitored folders.

**Comment by electrotype** [comment]
Maybe try: right-click on the folders you monitor and "Mark Folder Read", to mark all their messages as read. Then test again.

**Comment by jasineri** [comment]
_Unselect all "Mail/Feed folders to monitor" in the options and start again?_ did the trick! Thanks!
