### ISSUE TITLE
Watch other folders than INBOX

### ISSUE THREAD

**Issue by sphh** [electrotype/thunderbird-addon-scriptable-notifications#3]
Finally an extension, which enables me to display an icon to my liking in the system tray! Thanks.

I filter my emails into different mailboxes and it would be really great, if ScriptableNotifications could act on mails in those folder as well.

**Comment by electrotype** [comment]
May have a look in the future. Open to PRs.

More info in my other reply here: https://github.com/electrotype/thunderbird-addon-scriptable-notifications/issues/4#issuecomment-1271820528

**Comment by sphh** [comment]
I don't think it necessary to list all folders, because IMHO it would be enough to display the folders with the "When getting new messages for this account, always check this folder" flag set. Thus the number of possible folders does not get endless (which cannot be handled in a sensible way).

To set this flag, right-click on the folder in question, select `Properties ...` and then the tab `General Information`.

Re my changes to make a PR, please see my other reply https://github.com/electrotype/thunderbird-addon-scriptable-notifications/issues/4#issuecomment-1271879201

**Comment by electrotype** [comment]
I really would have to look into this more deeply, as our use cases seems to be different.

I'm not even sure what "When getting new messages for this account, always check this folder" does. Is that an IMAP thing that make the _server_ move some messages to some custom folders based on filters?

I don't even see the same property name as you under `General Information` (probably because I group all my accounts into the same global "Local Folder"):

<img width="357" alt="20221007_142341" src="https://user-images.githubusercontent.com/1643012/194625649-d37c174f-bba8-4c17-a914-882fbe691c49.png">

Of couse a PR with some steps to reproduce would be welcome.

**Comment by sphh** [comment]
You are right, that this option only shows up on mail folder in an IMAP account. There is no such option for local folders (I don't use them).

Is Thunderbird checking all local folders for new mail? That would explain our different experience: You use local folders and ScriptableNotification might be triggered on all new messages in all folder. I use IMAP and ScriptableNotification is only triggered on the folder marked as INBOX. I would be perfectly happy, if it were also triggered on those folders marked with "When getting new messages …". No additional settings required!

**Comment by electrotype** [comment]
Support for favorite folders now available in version 4.1.

Thanks for the feature @sphh !
